<a href="https://colab.research.google.com/github/wbfrench1/python_tutorial/blob/main/Pandas_MultiIindex.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np

In [4]:
In [1]: arrays = [
   ...:     ["bar", "bar", "baz", "baz", "foo", "foo", "qux", "qux"],
   ...:     ["one", "two", "one", "two", "one", "two", "one", "two"],
   ...: ]
   ...:

arrays

[['bar', 'bar', 'baz', 'baz', 'foo', 'foo', 'qux', 'qux'],
 ['one', 'two', 'one', 'two', 'one', 'two', 'one', 'two']]

In [9]:
tuples= list(zip(*arrays))

index = pd.MultiIndex.from_tuples(tuples, names=["first", "second"])
index

MultiIndex([('bar', 'one'),
            ('bar', 'two'),
            ('baz', 'one'),
            ('baz', 'two'),
            ('foo', 'one'),
            ('foo', 'two'),
            ('qux', 'one'),
            ('qux', 'two')],
           names=['first', 'second'])

In [11]:
s = pd.Series(np.random.randn(8), index=index)
s

first  second
bar    one      -1.455391
       two       0.118799
baz    one       0.613747
       two       0.602605
foo    one       0.319633
       two      -2.079724
qux    one      -0.087251
       two      -0.768844
dtype: float64

In [13]:
In [8]: iterables = [["bar", "baz", "foo", "qux"], ["one", "two"]]

In [9]: pd.MultiIndex.from_product(iterables, names=["first", "second"])

MultiIndex([('bar', 'one'),
            ('bar', 'two'),
            ('baz', 'one'),
            ('baz', 'two'),
            ('foo', 'one'),
            ('foo', 'two'),
            ('qux', 'one'),
            ('qux', 'two')],
           names=['first', 'second'])

In [14]:
In [10]: df = pd.DataFrame(
   ....:     [["bar", "one"], ["bar", "two"], ["foo", "one"], ["foo", "two"]],
   ....:     columns=["first", "second"],
   ....: )
   ....:

In [11]: pd.MultiIndex.from_frame(df)

MultiIndex([('bar', 'one'),
            ('bar', 'two'),
            ('foo', 'one'),
            ('foo', 'two')],
           names=['first', 'second'])

In [15]:
df

  first second
0   bar    one
1   bar    two
2   foo    one
3   foo    two

In [17]:
arrays = [
    np.array(["bar", "bar", "baz", "baz", "foo", "foo", "qux", "qux"]),
    np.array(["one", "two", "one", "two", "one", "two", "one", "two"]),
]


s = pd.Series(np.random.randn(8), index=arrays)

s

bar  one    1.032449
     two    1.214417
baz  one   -0.000296
     two    0.013094
foo  one   -0.716169
     two    0.465693
qux  one    1.037474
     two    2.585657
dtype: float64

In [18]:
df = pd.DataFrame(np.random.randn(8, 4), index=arrays)

df

                0         1         2         3
bar one -0.746901  0.372583 -2.050003 -1.323990
    two -0.864347 -1.938218 -0.644555  1.080187
baz one -0.359604 -0.683027  2.096352  0.382988
    two  1.356713  0.472250 -0.906374 -1.105763
foo one  0.875628 -0.577794 -1.035105 -1.578844
    two  0.235438 -1.304569  0.718205 -0.184105
qux one -0.512722  0.604420  1.120804 -0.978992
    two  0.256498 -3.030195  0.437560 -1.384212

In [20]:
df.index.names

FrozenList([None, None])

In [21]:
In [18]: df = pd.DataFrame(np.random.randn(3, 8), index=["A", "B", "C"], columns=index)

In [19]: df

first        bar                 baz                 foo                 qux  \
second       one       two       one       two       one       two       one
A      -0.474316 -1.811611  0.426911 -0.095980 -0.086624 -1.299740  1.535467
B       2.135742  0.013063 -0.046402 -0.357986  0.772866  0.580891 -2.405048
C      -1.127688  1.576419 -0.087565  0.595764 -0.837789  1.544349  0.796659

first
second       two
A       0.334449
B       0.798416
C      -0.234599

In [23]:
index

MultiIndex([('bar', 'one'),
            ('bar', 'two'),
            ('baz', 'one'),
            ('baz', 'two'),
            ('foo', 'one'),
            ('foo', 'two'),
            ('qux', 'one'),
            ('qux', 'two')],
           names=['first', 'second'])

In [22]:
In [20]: pd.DataFrame(np.random.randn(6, 6), index=index[:6], columns=index[:6])

first              bar                 baz                 foo
second             one       two       one       two       one       two
first second
bar   one    -0.385359  1.533505 -0.222800 -1.001638  0.222150  0.959886
      two    -0.079315 -1.218269 -0.285705  0.993751 -0.124898 -0.649122
baz   one     1.124918  0.818587 -1.080907 -1.465828  1.781943  0.143836
      two    -1.142316  0.084325  0.321598 -1.215849 -0.514869 -1.452527
foo   one     0.788411  1.135521 -1.325730  1.461269  0.145165  0.875498
      two    -1.322115  1.270770  0.745222 -0.867804 -0.940760  0.271658

In [26]:
index

MultiIndex([('bar', 'one'),
            ('bar', 'two'),
            ('baz', 'one'),
            ('baz', 'two'),
            ('foo', 'one'),
            ('foo', 'two'),
            ('qux', 'one'),
            ('qux', 'two')],
           names=['first', 'second'])

In [25]:
index.get_level_values(0)

Index(['bar', 'bar', 'baz', 'baz', 'foo', 'foo', 'qux', 'qux'], dtype='object', name='first')

In [27]:
index.get_level_values('first')

Index(['bar', 'bar', 'baz', 'baz', 'foo', 'foo', 'qux', 'qux'], dtype='object', name='first')

In [28]:
index.get_level_values('second')

Index(['one', 'two', 'one', 'two', 'one', 'two', 'one', 'two'], dtype='object', name='second')

In [29]:
df

first        bar                 baz                 foo                 qux  \
second       one       two       one       two       one       two       one
A      -0.474316 -1.811611  0.426911 -0.095980 -0.086624 -1.299740  1.535467
B       2.135742  0.013063 -0.046402 -0.357986  0.772866  0.580891 -2.405048
C      -1.127688  1.576419 -0.087565  0.595764 -0.837789  1.544349  0.796659

first
second       two
A       0.334449
B       0.798416
C      -0.234599

In [30]:
df['bar']

second       one       two
A      -0.474316 -1.811611
B       2.135742  0.013063
C      -1.127688  1.576419

In [32]:
df['bar']['one']
df['bar', 'one']

A   -0.474316
B    2.135742
C   -1.127688
Name: (bar, one), dtype: float64

In [35]:
s

bar  one    1.032449
     two    1.214417
baz  one   -0.000296
     two    0.013094
foo  one   -0.716169
     two    0.465693
qux  one    1.037474
     two    2.585657
dtype: float64

In [34]:
s['qux']

one    1.037474
two    2.585657
dtype: float64

In [36]:
In [29]: df.columns.levels  # original MultiIndex

FrozenList([['bar', 'baz', 'foo', 'qux'], ['one', 'two']])

In [41]:
df

first        bar                 baz                 foo                 qux  \
second       one       two       one       two       one       two       one
A      -0.474316 -1.811611  0.426911 -0.095980 -0.086624 -1.299740  1.535467
B       2.135742  0.013063 -0.046402 -0.357986  0.772866  0.580891 -2.405048
C      -1.127688  1.576419 -0.087565  0.595764 -0.837789  1.544349  0.796659

first
second       two
A       0.334449
B       0.798416
C      -0.234599

In [40]:
df[["foo","qux"]]

first        foo                 qux
second       one       two       one       two
A      -0.086624 -1.299740  1.535467  0.334449
B       0.772866  0.580891 -2.405048  0.798416
C      -0.837789  1.544349  0.796659 -0.234599

In [37]:
In [30]: df[["foo","qux"]].columns.levels  # sliced

FrozenList([['bar', 'baz', 'foo', 'qux'], ['one', 'two']])

In [39]:
df.columns

MultiIndex([('bar', 'one'),
            ('bar', 'two'),
            ('baz', 'one'),
            ('baz', 'two'),
            ('foo', 'one'),
            ('foo', 'two'),
            ('qux', 'one'),
            ('qux', 'two')],
           names=['first', 'second'])

In [44]:
df[["foo", "qux"]].columns

MultiIndex([('foo', 'one'),
            ('foo', 'two'),
            ('qux', 'one'),
            ('qux', 'two')],
           names=['first', 'second'])

In [43]:
new_mi = df[["foo", "qux"]].columns.remove_unused_levels()
new_mi

MultiIndex([('foo', 'one'),
            ('foo', 'two'),
            ('qux', 'one'),
            ('qux', 'two')],
           names=['first', 'second'])

In [46]:
new_mi.levels

FrozenList([['foo', 'qux'], ['one', 'two']])

Data alignment and using reindex

In [47]:
s

bar  one    1.032449
     two    1.214417
baz  one   -0.000296
     two    0.013094
foo  one   -0.716169
     two    0.465693
qux  one    1.037474
     two    2.585657
dtype: float64